name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Code coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out
